### ISSUE TITLE
error during build

### ISSUE THREAD

**Issue by coolcodecding** [akshayvernekar/esp_tensorflow_fmnist#1]
Im using a AI THINKER ESP32 CAM and tried to build your code folder. ESP-IDF works with other examples and I don't know, how to solve the issue. I have Ubunut 18.
Here is the code including the error i receive:

```
In file included from ../main/app_tensorflow.cc:15:
../main/include/app_camera.h:19:10: fatal error: esp_camera.h: No such file or directory
 #include "esp_camera.h"
          ^~~~~~~~~~~~~~
compilation terminated.
[969/974] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/image_util/image_util.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

```

**Comment by akshayvernekar** [comment]
It looks like you havent cloned the esp-camera submodule . I have updated the readme file , please follow the instructions as per the readme . Also note that I have tested the repository using IDF version 4, other versions might need some adjustment.

**Comment by akshayvernekar** [comment]
Closing this issue as there is no further activity.
